# Docker hub构建镜像示例，请替换密钥和用户名，手动触发，自动推送
name: Docker-hub镜像构建

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
   
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}/${{ github.event.inputs.version }}
          tags: |
            type=manual

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.repository }}:${{ github.event.inputs.version }}, ${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
